export const blogPosts = [
  {
    id: 1,
    title: "Export to PDF in Power Apps - The Best Way to Do It!",
    description:
      "Learn how to export data from Power Apps to PDF using Power Automate. This tutorial shows the easiest and most effective way to generate professional PDF documents directly from your Power Apps.",
    slug: "https://www.powerplatformexperts.com.au/blog/export-to-pdf-in-power-apps",
    date: "April 11, 2025",
    author: "Marcello Brocchi",
    readingTime: "6 min",
    category: "Power Apps",
    featured: false,
    youtubeId: "_mgLYllGY-Y",
    imagePath: null, // Default to null when using youtubeId
  },
  {
    id: 2,
    title: "Getting Started with Power Apps and Microsoft SQL Database",
    description:
      "Learn how to evolve your Power Apps development by connecting to Microsoft SQL databases. This comprehensive guide covers setting up an Azure SQL database and building applications.",
    slug: "https://www.powerplatformexperts.com.au/blog/power-apps-with-sql-database",
    date: "April 11, 2025",
    author: "Marcello Brocchi",
    readingTime: "8 min",
    category: "Power Apps",
    featured: false,
    youtubeId: "awsNLPGNI4w",
    imagePath: null,
  },
  {
    id: 3,
    title: "Power Apps PDF Function - The Best Way to Export to PDF?",
    description:
      "Discover how to use the new experimental PDF function in Power Apps to generate PDF documents directly from your applications without complex workarounds.",
    slug: "https://www.powerplatformexperts.com.au/blog/power-apps-pdf-function",
    date: "April 11, 2025",
    author: "Marcello Brocchi",
    readingTime: "4 min",
    category: "Power Apps",
    featured: false,
    youtubeId: "BiOCK1jDOMo",
    imagePath: null,
  },
  {
    id: 4,
    title: "File Attachments in Power Apps - The Best Way to Do Them",
    description:
      "Learn the best approach to implement file attachments in Power Apps using the new Power Automate action that makes uploading documents to SharePoint document libraries simple and efficient.",
    slug: "https://www.powerplatformexperts.com.au/blog/file-attachments-in-power-apps",
    date: "April 11, 2025",
    author: "Marcello Brocchi",
    readingTime: "5 min",
    category: "Power Apps",
    featured: false,
    youtubeId: "yC0W5am6M3Q",
    imagePath: null,
  },
  {
    id: 5,
    title: "How to Convert a Canva Design into a Microsoft Word Template",
    description:
      "Explore in-depth tutorials, tips, and best practices for mastering advanced Microsoft software techniques, including Excel, Power BI, Power Pivot, and more.",
    slug: "https://www.wordexperts.com.au/blog/convert-canva-to-word",
    date: "April 14, 2025",
    author: "Daniel Thomas",
    readingTime: "5 min",
    category: "Word",
    featured: false,
    youtubeId: null,
    imagePath: "/canva-to-word.webp",
  },
  {
    id: 6,
    title: "Ultimate Guide to Microsoft Word Templates",
    description:
      "What is a Word Template? Explore the benefits, types, and implementation of Microsoft Word templates for your organization. Learn how templates can ensure consistency and save valuable time.",
    slug: "https://www.wordexperts.com.au/blog/ultimate-guide-to-word-templates",
    date: "April 8, 2025",
    author: "Daniel Thomas",
    readingTime: "8 min",
    category: "Word",
    featured: false,
    youtubeId: null,
    imagePath: "/template.webp",
  },
  {
    id: 7,
    title:
      "The Hidden Risk of Spreadsheet Errors in Your Business—and How to Prevent Them",
    description:
      "Research shows that 88% of spreadsheets contain errors. Learn why spreadsheet errors are so common, how to identify warning signs, and practical strategies to prevent costly mistakes in your business.",
    slug: "https://www.excelexperts.com.au/blog/spreadsheet-errors-in-excel",
    date: "July 23, 2025",
    author: "Daniel Thomas",
    readingTime: "8 min",
    category: "Excel",
    featured: false,
    youtubeId: null,
    imagePath: "/blog/mistake.webp",
  },
  {
    id: 8,
    title: "20 Advanced Excel Shortcuts That Will Supercharge Your Workflow",
    description:
      "Master 20 advanced Excel shortcuts for Mac that will transform your productivity. From data analysis to formatting, these keyboard shortcuts will save you hours and impress your team.",
    slug: "https://www.excelexperts.com.au/blog/20-advanced-excel-shortcuts",
    date: "July 24, 2025",
    author: "Daniel Thomas",
    readingTime: "6 min",
    category: "Excel",
    featured: false,
    youtubeId: null,
    imagePath: "/blog/shortcut.webp",
  },
  {
    id: 9,
    title: "10 Custom Excel Shortcuts Using Macros (With Practical Use Cases)",
    description:
      "Learn how to create your own Excel shortcuts using macros to automate repetitive tasks. Discover 10 practical custom shortcuts that will supercharge your productivity and save you hours of work.",
    slug: "https://www.excelexperts.com.au/blog/custom-excel-shortcuts-with-macros",
    date: "July 24, 2025",
    author: "Daniel Thomas",
    readingTime: "7 min",
    category: "Excel",
    featured: false,
    youtubeId: null,
    imagePath: "/blog/custom.webp",
  },
  {
    id: 10,
    title:
      "Fields and Repeating Data in Word: Best Practices for Business Templates",
    description:
      "Learn how to use Word's fields to transform static templates into dynamic, error-resistant tools. Master REF fields, document properties, and content controls to eliminate manual data entry and reduce costly errors.",
    slug: "https://www.wordexperts.com.au/blog/fields-and-repeating-data-in-word",
    date: "July 24, 2025",
    author: "Daniel Thomas",
    readingTime: "12 min",
    category: "Word",
    featured: false,
    imagePath: "/blog/waste.webp",
  },
  {
    id: 11,
    title: "Creating Word Templates for Legal Firms: Best Practices",
    description:
      "Learn how to create professional, efficient Word templates for legal firms. Discover best practices for reducing errors, ensuring consistency, and protecting client confidentiality with smart template design.",
    slug: "https://www.wordexperts.com.au/blog/word-templates-for-legal-firms",
    date: "July 25, 2025",
    author: "Daniel Thomas",
    readingTime: "10 min",
    category: "Word",
    featured: false,
    imagePath: "/blog/legal.webp",
  },
  {
    id: 12,
    title: "Your Access Database Isn't Dead — It Just Needs a Cloud Strategy",
    description:
      "Don't abandon your Microsoft Access database. Learn how to modernise it with cloud technologies like Azure SQL, SharePoint, and Power Platform while keeping your existing forms, reports, and business logic intact.",
    slug: "https://www.accessexperts.com.au/blog/your-access-database-needs-a-cloud-strategy",
    date: "July 28, 2025",
    author: "Daniel Thomas",
    readingTime: "8 min",
    category: "Cloud Migration",
    featured: false,
    youtubeId: null,
    imagePath: "/blog/cloud-strategy/plane.webp",
  },
  {
    id: 13,
    title:
      "Hybrid Access Solutions: Connect to Power Apps Without Losing What Works",
    description:
      "Learn how to modernise your Microsoft Access database with Power Platform without losing your existing forms, reports, and VBA code. Discover hybrid solutions that connect Access to Dataverse and Power Apps.",
    slug: "https://www.accessexperts.com.au/blog/using-power-platform-with-access-database",
    date: "July 30, 2025",
    author: "Access Experts Team",
    readingTime: "14 min",
    category: "Dataverse",
    featured: false,
    youtubeId: null,
    imagePath: "/blog/platform-database/resuscitate.webp",
  },
  {
    id: 14,
    title:
      "Google Docs vs Microsoft Word: Which Is Best for Enterprise Workflows?",
    description:
      "Compare Google Docs and Microsoft Word for enterprise use. Discover why many organisations migrate from Google Docs to Word for advanced features, compliance, automation, and scalability needs.",
    slug: "https://www.wordexperts.com.au/blog/google-docs-vs-microsoft-word",
    date: "August 27, 2025",
    author: "Rochelle Robinson",
    readingTime: "12 min",
    category: "Word",
    featured: false,
    youtubeId: null,
    imagePath: "/blog/google-docs-or-word.webp",
  },
  {
    id: 15,
    title: "Power BI for Financial Services",
    description:
      "Discover how Power BI empowers financial organisations to turn raw data into actionable insights for compliance, risk management, and business growth.",
    slug: "https://www.powerplatformexperts.com.au/blog/power-bi-for-financial-services",
    date: "October 1, 2025",
    author: "Power Platform Team",
    readingTime: "10 min",
    category: "Power BI",
    featured: false,
    youtubeId: null, // Set to null when using custom image
    imagePath: "/blog/financial/financial-services.webp",
  },
  {
    id: 16,
    title: "PDF to Word Conversion That Works for Business",
    description:
      "Discover why professional PDF to Word conversion matters for business. Learn about accuracy, security, and formatting challenges that free converters can't handle.",
    slug: "https://www.wordexperts.com.au/blog/pdf-to-word-conversion",
    date: "October 3, 2025",
    author: "Aleisha Robinson",
    readingTime: "10 min",
    category: "Conversions",
    featured: false,
    youtubeId: null,
    imagePath: "/blog/pdf-to-word-template.webp",
  },
  {
    id: 17,
    title: "Power BI in Healthcare Analytics: Transforming Patient Outcomes",
    description:
      "Discover how Power BI is revolutionising healthcare analytics with real-time dashboards that improve patient outcomes, reduce readmissions, and optimise hospital operations.",
    slug: "https://www.powerplatformexperts.com.au/blog/power-bi-in-healthcare-analytics",
    date: "October 3, 2025",
    author: "Scott Robinson",
    readingTime: "8 min",
    category: "Power BI",
    featured: true,
    youtubeId: null,
    imagePath: "/blog/healthcare/healthcare.webp",
  },
  {
    id: 18,
    title: "Microsoft Access vs. Excel: When to Use Which for Your Business",
    description:
      "Discover when to use Microsoft Access versus Excel for your Australian business data management. Learn the key differences, benefits, and how to leverage both tools together for optimal efficiency.",
    slug: "https://www.accessexperts.com.au/blog/access-vs-excel",
    date: "October 23, 2025",
    author: "Daniel Thomas",
    readingTime: "12 min",
    category: "Access",
    featured: false,
    youtubeId: null,
    imagePath: "/blog/access-vs-excel.webp",
  },
  {
    id: 19,
    title: "Why Dropbox Fails with Access Databases: Better Cloud Solutions",
    description:
      "Storing Microsoft Access databases in Dropbox leads to corruption, data loss, and conflicts. Learn why this approach fails and discover reliable alternatives like SQL Server and Azure SQL for secure multi-user access.",
    slug: "https://www.accessexperts.com.au/blog/why-dropbox-fails-with-access-databases",
    date: "January 29, 2025",
    author: "Scott Robinson",
    readingTime: "7 min",
    category: "Access",
    featured: true,
    youtubeId: null,
    imagePath: "/blog/dropbox/access-to-dropbox.webp",
  },
  {
    id: 20,
    title:
      "Power BI Licensing Costs Spiraling? The Hidden Expenses Killing Your ROI",
    description:
      "Discover why 40% of businesses overpay for Power BI licenses. Learn the hidden costs, break-even points, and smart licensing strategies that could save your business $20,000-80,000 per year.",
    slug: "https://www.powerplatformexperts.com.au/blog/power-bi-licensing-costs",
    date: "December 04, 2025",
    author: "Scott Robinson",
    readingTime: "12 min",
    category: "Power BI",
    featured: false,
    youtubeId: null,
    imagePath: "/blog/costs/money.webp",
  },
  {
    id: 21,
    title: "Use SharePoint Lists just like a Relational Database in Power Apps",
    description:
      "In this tutorial, Marcello gives you a quick introduction into how to use SharePoint lists as a data source in Power Apps and how they may work as a Relational Database.",
    slug: "https://www.powerplatformexperts.com.au/blog/sharepoint-lists",
    date: "April 20, 2025",
    author: "Marcello Brocchi",
    readingTime: "5 min",
    category: "SharePoint",
    featured: false,
    youtubeId: "Bea5aP-OpZg",
    imagePath: null,
  },
  {
    id: 22,
    title:
      "How to Get Live MYOB & Xero Data into Power BI — No More Manual Exports",
    description:
      "Tired of CSV exports and stale reports? Learn how to connect live MYOB and Xero data into Power BI using modern OData feeds like OdataLink, plus implementation strategies from Power Platform Experts.",
    slug: "https://www.powerplatformexperts.com.au/blog/xero-to-power-bi",
    date: "November 20, 2025",
    author: "Scott Robinson",
    readingTime: "10 min",
    category: "Power BI",
    featured: false,
    youtubeId: null,
    imagePath: "/blog/xero/xero-to-power-bi.webp",
  },
  {
    id: 23,
    title: "Your Access Database Just Hit 2GB... Now What? A Survival Guide",
    description:
      "The 2GB limit crisis hits without warning. Learn why it happens, how to recognize the warning signs, and discover immediate fixes vs long-term solutions including migration paths to SQL Server and Azure.",
    slug: "https://www.accessexperts.com.au/blog/2gb-access-database-limit",
    date: "January 28, 2025",
    author: "Scott Robinson",
    readingTime: "15 min",
    category: "Database",
    featured: true,
    youtubeId: null,
    imagePath: "/blog/2gb/stop.webp",
  },
];
