export const blogPosts = [
  {
    id: 1,
    title: "Export to PDF in Power Apps - The Best Way to Do It!",
    description:
      "Learn how to export data from Power Apps to PDF using Power Automate. This tutorial shows the easiest and most effective way to generate professional PDF documents directly from your Power Apps.",
    slug: "https://www.powerplatformexperts.com.au/blog/export-to-pdf-in-power-apps",
    date: "April 11, 2025",
    author: "Marcello Brocchi",
    readingTime: "6 min",
    category: "Power Apps",
    featured: true,
    youtubeId: "_mgLYllGY-Y",
    imagePath: null, // Default to null when using youtubeId
  },
  {
    id: 2,
    title: "Getting Started with Power Apps and Microsoft SQL Database",
    description:
      "Learn how to evolve your Power Apps development by connecting to Microsoft SQL databases. This comprehensive guide covers setting up an Azure SQL database and building applications.",
    slug: "https://www.powerplatformexperts.com.au/blog/power-apps-with-sql-database",
    date: "April 11, 2025",
    author: "Marcello Brocchi",
    readingTime: "8 min",
    category: "Power Apps",
    featured: false,
    youtubeId: "awsNLPGNI4w",
    imagePath: null,
  },
  {
    id: 3,
    title: "Power Apps PDF Function - The Best Way to Export to PDF?",
    description:
      "Discover how to use the new experimental PDF function in Power Apps to generate PDF documents directly from your applications without complex workarounds.",
    slug: "https://www.powerplatformexperts.com.au/blog/power-apps-pdf-function",
    date: "April 11, 2025",
    author: "Marcello Brocchi",
    readingTime: "4 min",
    category: "Power Apps",
    featured: false,
    youtubeId: "BiOCK1jDOMo",
    imagePath: null,
  },
  {
    id: 4,
    title: "File Attachments in Power Apps - The Best Way to Do Them",
    description:
      "Learn the best approach to implement file attachments in Power Apps using the new Power Automate action that makes uploading documents to SharePoint document libraries simple and efficient.",
    slug: "https://www.powerplatformexperts.com.au/blog/file-attachments-in-power-apps",
    date: "April 11, 2025",
    author: "Marcello Brocchi",
    readingTime: "5 min",
    category: "Power Apps",
    featured: false,
    youtubeId: "yC0W5am6M3Q",
    imagePath: null,
  },
  {
    id: 5,
    title: "How to Convert a Canva Design into a Microsoft Word Template",
    description:
      "Explore in-depth tutorials, tips, and best practices for mastering advanced Microsoft software techniques, including Excel, Power BI, Power Pivot, and more.",
    slug: "https://www.wordexperts.com.au/blog/convert-canva-to-word",
    date: "April 14, 2025",
    author: "Daniel Thomas",
    readingTime: "5 min",
    category: "Conversions",
    featured: false,
    youtubeId: null,
    imagePath: "/canva-to-word.webp",
  },
  {
    id: 6,
    title: "Ultimate Guide to Microsoft Word Templates",
    description:
      "What is a Word Template? Explore the benefits, types, and implementation of Microsoft Word templates for your organization. Learn how templates can ensure consistency and save valuable time.",
    slug: "https://www.wordexperts.com.au/blog/ultimate-guide-to-word-templates",
    date: "April 8, 2025",
    author: "Daniel Thomas",
    readingTime: "8 min",
    category: "Templates",
    featured: false,
    youtubeId: null,
    imagePath: "/template.webp",
  },
  {
    id: 7,
    title:
      "The Hidden Risk of Spreadsheet Errors in Your Business—and How to Prevent Them",
    description:
      "Research shows that 88% of spreadsheets contain errors. Learn why spreadsheet errors are so common, how to identify warning signs, and practical strategies to prevent costly mistakes in your business.",
    slug: "https://www.excelexperts.com.au/blog/spreadsheet-errors-in-excel",
    date: "July 23, 2025",
    author: "Daniel Thomas",
    readingTime: "8 min",
    category: "Spreadsheets",
    featured: false,
    youtubeId: null,
    imagePath: "/blog/mistake.webp",
  },
  {
    id: 8,
    title: "20 Advanced Excel Shortcuts That Will Supercharge Your Workflow",
    description:
      "Master 20 advanced Excel shortcuts for Mac that will transform your productivity. From data analysis to formatting, these keyboard shortcuts will save you hours and impress your team.",
    slug: "https://www.excelexperts.com.au/blog/20-advanced-excel-shortcuts",
    date: "July 24, 2025",
    author: "Daniel Thomas",
    readingTime: "6 min",
    category: "Shortcuts",
    featured: false,
    youtubeId: null,
    imagePath: "/blog/shortcut.webp",
  },
  {
    id: 9,
    title: "10 Custom Excel Shortcuts Using Macros (With Practical Use Cases)",
    description:
      "Learn how to create your own Excel shortcuts using macros to automate repetitive tasks. Discover 10 practical custom shortcuts that will supercharge your productivity and save you hours of work.",
    slug: "https://www.excelexperts.com.au/blog/custom-excel-shortcuts-with-macros",
    date: "July 24, 2025",
    author: "Daniel Thomas",
    readingTime: "7 min",
    category: "Shortcuts",
    featured: false,
    youtubeId: null,
    imagePath: "/blog/custom.webp",
  },
  {
    id: 10,
    title:
      "Fields and Repeating Data in Word: Best Practices for Business Templates",
    description:
      "Learn how to use Word's fields to transform static templates into dynamic, error-resistant tools. Master REF fields, document properties, and content controls to eliminate manual data entry and reduce costly errors.",
    slug: "https://www.wordexperts.com.au/blog/fields-and-repeating-data-in-word",
    date: "July 24, 2025",
    author: "Daniel Thomas",
    readingTime: "12 min",
    category: "Templates",
    featured: false,
    imagePath: "/blog/waste.webp",
  },
  {
    id: 11,
    title: "Creating Word Templates for Legal Firms: Best Practices",
    description:
      "Learn how to create professional, efficient Word templates for legal firms. Discover best practices for reducing errors, ensuring consistency, and protecting client confidentiality with smart template design.",
    slug: "https://www.wordexperts.com.au/blog/word-templates-for-legal-firms",
    date: "July 25, 2025",
    author: "Daniel Thomas",
    readingTime: "10 min",
    category: "Legal",
    featured: false,
    imagePath: "/blog/legal.webp",
  },
  {
    id: 12,
    title: "Your Access Database Isn't Dead — It Just Needs a Cloud Strategy",
    description:
      "Don't abandon your Microsoft Access database. Learn how to modernise it with cloud technologies like Azure SQL, SharePoint, and Power Platform while keeping your existing forms, reports, and business logic intact.",
    slug: "https://www.accessexperts.com.au/blog/your-access-database-needs-a-cloud-strategy",
    date: "July 28, 2025",
    author: "Daniel Thomas",
    readingTime: "8 min",
    category: "Cloud Migration",
    featured: false,
    youtubeId: null,
    imagePath: "/blog/cloud-strategy/plane.webp",
  },
  {
    id: 13,
    title:
      "Hybrid Access Solutions: Connect to Power Apps Without Losing What Works",
    description:
      "Learn how to modernise your Microsoft Access database with Power Platform without losing your existing forms, reports, and VBA code. Discover hybrid solutions that connect Access to Dataverse and Power Apps.",
    slug: "https://www.accessexperts.com.au/blog/using-power-platform-with-access-database",
    date: "July 30, 2025",
    author: "Access Experts Team",
    readingTime: "14 min",
    category: "Dataverse",
    featured: true,
    youtubeId: null,
    imagePath: "/blog/platform-database/resuscitate.webp",
  },
];
