export const goneUrls = [
  "/services/by-business-solution/dashboards/attachment/power-pivot-and-dax/",

  "/services/by-business-solution/dashboards/attachment/user-interface-slicer-2/",

  "/services/by-business-solution/database-development-and-solutions/attachment/microsoft-asp-dot-net-icon-logo/",

  "/services/by-business-solution/vba-macro-development/attachment/modern-computer-with-keyboard-and-mouse-on-table-showing-charts/",

  "/services/by-business-solution/vba-macro-development/attachment/programming/",

  "/services/by-business-solution/vba-macro-development/attachment/unlock-success_digital-lock/",
  "/services/microsoft-access/attachment/access-experts-logo/",

  "/services/microsoft-access/attachment/microsoft-access-database-consulting-services/",

  "/services/microsoft-access/attachment/microsoft-access-online-icons/",

  "/services/microsoft-excel/attachment/dashboard_pie-chart_bar-graph_reporting-solutions_microsoft-excel-experts/",

  "/services/microsoft-excel/attachment/dashboards-and-reporting-solutions_microsoft-excel-experts/",
  "/services/microsoft-excel/attachment/dashboards-icon/",

  "/services/microsoft-excel/attachment/excel-custom-design-and-development-2/",

  "/services/microsoft-excel/attachment/excel-custom-design-and-development_microsoft-excel-experts/",

  "/services/microsoft-excel/attachment/excel-data-integration_microsoft-excel-experts/",
  "/services/microsoft-excel/attachment/excel-formula-function-icon/",

  "/services/microsoft-excel/attachment/microsoft-access-consulting-services_access-experts/",

  "/services/microsoft-excel/attachment/microsoft-database-solutions_microsoft-access-experts_sharepoint_sql-server_azure_asp-dot-net/",

  "/services/microsoft-excel/attachment/microsoft-excel-consulting-services_microsoft-excel-experts/",

  "/services/microsoft-excel/attachment/microsoft-excel_pivot-tables-charts-and-reporting-solutions/",

  "/blog/did-you-know-we-work-with-most-microsoft-technologies/attachment/microsoft-logo-centered/",

  "/blog/did-you-know-we-work-with-most-microsoft-technologies/attachment/microsoft-logo/",

  "/blog/office-experts-is-now-on-linkedin/attachment/linked-in_clipart/",

  "/faq-items/do-you-come-onsite-or-work-remotely/attachment/onsite-services/",

  "/faq-items/do-you-come-onsite-or-work-remotely/attachment/team-viewer-button/",

  "/faq-items/how-can-we-pay-you/attachment/payment-method_direct-debit/",
  "/faq_category/our-business-2/",
  "/home/attachment/microsoft-access-consulting-services/",
  "/home/attachment/microsoft-excel-consulting-services/",
  "/home/attachment/microsoft-office-consulting/",

  "/home/attachment/microsoft-office-consulting_office-experts-group_excel-experts_access-experts_word-experts-365-experts_powerpoint-experts/",
  "/home/attachment/microsoft-power-bi-consulting-services/",
  "/home/attachment/microsoft-powerpoint-consulting-services/",
  "/home/attachment/microsoft-word-consulting-services/",
  "/home/attachment/office-365-consulting-services/",
  "/services/attachment/microsoft-certified-solutions-associate/",

  "/services/by-business-solution/3rd-party-application-or-office-integration/attachment/3d-database-structure-over-white-in-black-and-blue-in-a-reflective-material/",

  "/services/by-business-solution/attachment/custom-office-solutions-2/",

  "/services/by-business-solution/dashboards/attachment/pivot-tables/",

  "/services/microsoft-excel/attachment/microsoft-office-365-consulting-services/",

  "/services/microsoft-excel/attachment/microsoft-office-microsoft-excel-integration_microsoft-office-experts-group_microsoft-excel-experts/",

  "/services/microsoft-excel/attachment/microsoft-power-bi-consulting-services_microsoft-excel-experts/",

  "/services/microsoft-excel/attachment/microsoft-powerapps_microsoft-excel-experts/",

  "/services/microsoft-excel/attachment/microsoft-sharepoint_integration_microsoft-excel-experts/",

  "/services/microsoft-excel/attachment/upgrade-microsoft-excel_microsoft-excel-experts/",

  "/services/microsoft-excel/excel-support/attachment/business-handshake-through-a-laptop-screen/",

  "/services/microsoft-excel/excel-support/attachment/business-success/",

  "/services/microsoft-excel/excel-support/attachment/mexican-businesswoman-talking-with-colleague-on-smartphone/",

  "/services/microsoft-excel/excel-support/attachment/office-experts-consultants-servicing-all-of-australia/",

  "/services/microsoft-excel/upgrades-and-migration/attachment/businessman-using-mouse-global-networking-data-exchanges-and-payments-online-shopping-with-icon-customer-connection-on-worldwide-information-background-m-banking-and-omni-channel-multichannel/",

  "/services/microsoft-excel/upgrades-and-migration/attachment/data-migration-2/",

  "/services/microsoft-office-365/attachment/microsoft-office-365-implementation_microsoft-office-365-experts/",

  "/services/microsoft-office-365/attachment/office-365-migration-consulting-services/",

  "/services/microsoft-power-platform/attachment/microsoft-power-automate_logo_100x100/",

  "/services/microsoft-power-platform/attachment/microsoft-power-platform_logo_100x100/",

  "/services/microsoft-powerpoint/attachment/microsoft-office-365_logo-header/",

  "/services/microsoft-powerpoint/attachment/microsoft-powerpoint-presentation_-logoheader/",
  "/services/microsoft-word/attachment/accessibility-desktop/",
  "/services/microsoft-word/attachment/classroom-training-icon/",

  "/services/microsoft-word/attachment/companies-and-organisations-networking/",
  "/services/microsoft-word/attachment/corporate-identity-image/",

  "/services/microsoft-word/attachment/custom-toolbars-and-ribbons-2/",

  "/services/microsoft-word/attachment/custom-toolbars-and-ribbons-image/",
  "/services/microsoft-word/attachment/fill-in-form-icon/",
  "/services/microsoft-word/attachment/government-departments-2/",
  "/services/microsoft-word/attachment/government_departments/",
  "/tag/access-database/",
  "/tag/analysis/",
  "/tag/azure/",
  "/tag/coders/",
  "/tag/consultant/",
  "/tag/consulting/",
  "/tag/database-solutions/",
  "/tag/design/",
  "/tag/development/",
  "/tag/excel-spreadsheet/",
  "/tag/excel-work/",
  "/tag/https/",
  "/tag/linkedin/",
  "/tag/microsoft-access/",
  "/tag/microsoft-consulting/",
  "/tag/microsoft-excel/",
  "/tag/microsoft-powerpoint/",
  "/tag/microsoft-services/",
  "/tag/microsoft-technology/",
  "/tag/microsoft-word/",
  "/tag/microsoft/",
  "/tag/mobile-friendly/",
  "/tag/new-website/",
  "/tag/office-experts-group/",
  "/tag/officeexperts-com-au/",
  "/tag/programmers/",
  "/tag/responsive-design/",
  "/tag/secure/",
  "/tag/sharepoint/",
  "/tag/sql-server/",
  "/tag/ssl/",
  "/tag/troubleshooting/",
  "/tag/user-friendly/",
  "/tag/web-site/",
  "/tag/website/",
  "/tag/word-designers/",
  "/tag/wordpress/",
  "/tag/www-officeexperts-com-au/",

  "/testimonials/algra-enterprises-trading-as-groovy-glass/attachment/groovy-glass_logo/",
  "/testimonials/arrow-energy/attachment/arrow-energy-2/",
  "/testimonials/asbuild-nt/attachment/asbuild-nt_logo/",
  "/testimonials/autokeepers/attachment/autokeepers_logo_150x24/",

  "/testimonials/autokeepers/attachment/south-gippsland-water_logo_150x63/",

  "/testimonials/burpengary-state-secondary-college/attachment/burpengary-state-secondary-college-2/",

  "/testimonials/bus-coach-international/attachment/bus-coach-international_logo/",
  "/testimonials/cars-co/attachment/cars-co-australia_logo/",

  "/testimonials/electrical-estimating-solutions/attachment/breast-cancer-institute-2/",

  "/testimonials/electrical-estimating-solutions/attachment/electrical-estimating-solutions/",

  "/testimonials/electrical-estimating-solutions/attachment/environmental-monitoring-services-2/",

  "/testimonials/electrical-estimating-solutions/attachment/mortgage-choice-2/",

  "/testimonials/electrical-estimating-solutions/attachment/shadforth-financial-group/",

  "/testimonials/electrical-estimating-solutions/attachment/solar-wise-2/",

  "/testimonials/electrical-estimating-solutions/attachment/the-money-institute-2/",

  "/testimonials/eps-environmental-property-services/attachment/eps_environmental-property-services-logo/",

  "/testimonials/essential-property-solutions/attachment/essential-property-solutions/",

  "/testimonials/familycare/attachment/testimonial_familycare_excel-experts/",

  "/testimonials/flow-high-performance/attachment/flow-high-performance_logo/",
  "/testimonials/highforce/attachment/highforce_logo/",

  "/testimonials/holistic-athlete-development/attachment/holistic-athlete-development_logo/",

  "/testimonials/link-strata-management/attachment/link-strata-management-2/",

  "/testimonials/mbp-consulting-pty-ltd-trading-as-horizon2technologies/attachment/horizon2technologies_logo/",
  "/testimonials/metro-trains/attachment/metro-trains-2/",
  "/testimonials/muchachos-pty-ltd/attachment/flx_fuzzy-log-x_logo/",
  "/testimonials/queensland-rail-2/",

  "/testimonials/rook-sheu/attachment/rook-partners_rook-sheu-ptd-ltd_logo/",
  "/testimonials/solarwise/",
  "/3rd-party-product-integration",
  "/access-support",
  "/access-online",
  "/mad-clarity",
  "/services/by-business-solution/3rd-party-application-or-office-integration/attachment/integration-cogs",
  "/testimonials/mbp-consulting-pty-ltd-trading-as-horizon2technologies",
  "/testimonials/trackspares/attachment/trackspares-main-logo",
  "/testimonials/jemena-asset-management-pty-ltd/attachment/jemena_logo",
  "/author/ppexperts",
  "/services/attachment/microsoft-partner-logo-multiline-black",
  "/services/microsoft-office/attachment/microsoft-office-add-ins-icon",
  "/testimonials/cars-co",
  "/services/microsoft-access/attachment/integration-api-logo-icon",
  "/faq-items/how-can-we-pay-you/attachment/payment-method_visa",
  "/testimonials/east-global-finance/attachment/east_global_finance",
  "/testimonials/dulux-group",
  "/services/by-business-solution/attachment/upgrades-and-migration-3",
  "/testimonials/cindy-geer",
  "/testimonials/gymnastics-australia/attachment/gymnastics-australia_logo",
  "/services/microsoft-excel/attachment/upgrade-microsoft-excel-icon",
  "/faq-items/how-can-we-pay-you/attachment/payment-method_amex",
  "/services/microsoft-word/attachment/reduce-repetition-increase-productivity",
  "/testimonials/algra-enterprises-trading-as-groovy-glass",
  "/services/attachment/microsoft-certified-professional",
  "/services/microsoft-office-365/attachment/app-and-custom-development-2",
  "/testimonials/facade-resolutions-pty-ltd",
  "/testimonials/traffic-act",
  "/blog/did-you-know-we-work-with-most-microsoft-technologies",
  "/testimonials/windowline",
  "/testimonials/environmental-monitoring-services/attachment/artisan-ornaments-logo",
  "/faq-items/how-can-we-pay-you/attachment/payment-method_company-cheque",
  "/services/microsoft-excel/data-manipulation/attachment/netwok-hologram-over-young-woman-s-face",
  "/testimonials/lifestyle-solutions",
  "/author/patrick",
  "/testimonials/the-money-institute",
  "/dulux-group",
  "/testimonials/transgrid",
  "/faq-items/do-you-come-onsite-or-work-remotely/attachment/skype-button",
  "/testimonials/familycare",
  "/testimonials/mortgage-choice",
  "/services/microsoft-office-365/cloud-backup-with-onedrive/attachment/cloud-database",
  "/tag/avada-theme",
  "/blog/at-your-service",
  "/office-excel-access-and-word-experts-wollongong",
  "/services/by-business-solution/dashboards/attachment/key-performance-indicators-kpi",
  "/testimonials/metro-trains",
  "/services/microsoft-word/attachment/companies-and-organisations-presentation",
  "/testimonials/gymnastics-australia",
  "/blog/office-experts-website",
  "/testimonials/persal-and-co",
  "/services/microsoft-excel/attachment/support-icon",
  "/services/microsoft-excel/support-icon",
  "/testimonials/staintec-pty-ltd",
  "/testimonials/brett-butler",
  "/testimonials/van-zeller-communications",
  "/testimonials/jemena-asset-management-pty-ltd",
  "/testimonials/autokeepers",
  "/services/by-business-solution/vba-macro-development/attachment/lets-delve-into-this-code",
  "/testimonials/burpengary-state-secondary-college",
  "/testimonials/smartcool-systems-australia",
  "/testimonials/bl-civil",
  "/testimonials/electrical-estimating-solutions/attachment/chill-it-2",
  "/testimonials/bekaert",
  "/testimonials/environmental-monitoring-services",
  "/blog/office-experts-the-best-excel-consultants",
  "/testimonials/south-gippsland-water",
  "/testimonials/buildcorp/attachment/buildcorp",
  "/faq-items/how-do-you-charge",
  "/testimonials/private-wealth-partners-group-pty-ltd",
  "/testimonials/herron-todd-white",
  "/testimonials/east-global-finance",
  "/testimonials/advance-scanning-services",
  "/testimonials/coates-hire-operations-pty-ltd",
  "/testimonials/maitland-public-school",
  "/testimonials/mayers-fine-food",
  "/testimonials",
  "/testimonials/lovelight-blinds",
  "/testimonials/rook-sheu",
  "/blog/office-experts-the-best-excel-consultants/attachment/expert-highlighted-in-green",
  "/testimonials/page/4",
  "/category/blog",
  "/services/microsoft-office/microsoft-office-add-ins-icon",
  "/testimonials/electrical-estimating-solutions",
  "/hyundai-construction-equipment-australia-2",
  "/category/uncategorized",
  "/services/by-business-solution/dashboards/key-performance-indicators-kpi",
  "/services/by-business-solution/3rd-party-application-or-office-integration/attachment/businessman-pushing-interface-with-social-icons",
  "/testimonials/containerspace",
  "/testimonials/electrical-estimating-solutions/attachment/window-line",
  "/services/by-business-solution/3rd-party-application-or-office-integration/attachment/businessman-on-blurred-background-holding-3d-rendering-group-of-blue-people",
  "/tag/microsoft-office",
  "/services/microsoft-powerpoint/attachment/classroom-training-icon-2",
  "/services/microsoft-excel/attachment/microsoft-office-microsoft-excel-integration",
  "/faq-items/do-we-service-international-clients",
  "/services/microsoft-excel/microsoft-office-microsoft-excel-integration",
  "/blog/our-range-of-services-is-broader-than-you-may-think",
  "/testimonials/eps-environmental-property-services",
  "/services/microsoft-word/attachment/corporate-global-template-solution-image",
  "/testimonials/bus-coach-international",
  "/testimonials/flow-high-performance",
  "/services/microsoft-word/attachment/upgrade-microsoft-word-icon",
  "/services/microsoft-word/attachment/custom-toolbars-and-ribbons-2",
  "/testimonials/page/5",
  "/testimonials/page/6",
  "/services/microsoft-power-platform/attachment/microsoft-power-pages_logo_100x100",
  "/faq-items/is-our-information-kept-confidential",
  "/faq-items/do-you-come-onsite-or-work-remotely",
  "/faq_category/our-business",
  "/faq-items/what-skills-do-you-have-in-your-company",
  "/faq-items",
  "/services/microsoft-office/attachment/online-solutions-icon",
  "/services/microsoft-excel/upgrades-and-migration/attachment/cloud-migration-2",
  "/testimonials/lowes-petroleum-service",
  "/testimonials/marys-house-services",
  "/testimonials/tla-australia-ltd",
  "/testimonials/highforce",
  "/testimonials/buildcorp",
  "/testimonials/artisan-ornaments",
  "/services/microsoft-word/attachment/adobe-to-word-logo",
  "/testimonials/trackspares",
  "/services/microsoft-word/microsoft-word-quick-parts-logo-icon",
  "/testimonials/hyde-park-inn",
  "/faq-items/where-are-we-located",
  "/faq_category/our-business-1",
  "/services/microsoft-excel/upgrades-and-migration/cloud-migration-2",
  "/testimonials/electrical-estimating-solutions/attachment/smartcool-systems-australia",
  "/faq-items/how-can-we-pay-you",
  "/testimonials/electrical-estimating-solutions/attachment/uniting-care-australia",
  "/testimonials/page/3",
  "/testimonials/muchachos-pty-ltd",
  "/faq-items/didnt-find-the-answer-to-your-question",
  "/testimonials/east-global-finance/attachment/marys_house_services",
  "/blog/remote-access-is-preferred-by-most-of-our-clients",
  "/tag/coding",
  "/tag/programming",
  "/services/by-business-solution/dashboards/attachment/user-interface-slicer-1",
  "/testimonials/page/8",
  "/page-sitemap.xml",
  "/sitemap_index.xml",
  "/www.officeexperts.com.au/contact-us/",
  "/faq-items/how-can-we-pay-you/payment-method_mastercard/",
  "/faq-items/how-can-we-pay-you/attachment/payment-method_mastercard/",
  "/testimonials/persal-and-co/attachment/persal-and-co_logo/",
  "/services/microsoft-word/attachment/microsoft-word-quick-parts-logo-icon/",
  "/testimonials/page/2/",
  "/testimonials/hyundai-construction-equipment-australia/",
  "/testimonials/warringtonfire-australia-pty-ltd/",
  "/blog/office-experts-is-now-on-linkedin/",
  "/testimonials/hitec-fluid-power-pty-ltd/",
  "/testimonials/asbuild-nt/",
  "/home/attachment/office-experts_excel-experts_dashboard-monitoring/",
  "/testimonials/electrical-estimating-solutions/attachment/transgrid/",
  "/home/attachment/excel-experts-logo/",
  "/services/by-business-solution/dashboards/attachment/dashboard-reporting/",
  "/fusion_tb_category/footer/",
  "/services/by-business-solution/dashboards/attachment/user-interface-timeline/",
  "/slide-page/homepage-slider/",
  "/element_category/elements/",
  "/element_category/sections/",
  "/testimonials/electrical-estimating-solutions/attachment/transgrid/",
  "/fusion_tb_category/header/",
  "/element_category/columns/",
  "/testimonials/electrical-estimating-solutions/attachment/lend-lease/",
  "/by-business-solution",
].map((url) => url.toLowerCase());
